# Generated by Django 4.2.4 on 2023-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0002_mesajob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesajob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mesajob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
