# Generated by Django 4.2.4 on 2023-08-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0005_alter_mesajob_relative_output_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='exclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='scope',
            field=models.TextField(default='1.1.1.1'),
            preserve_default=False,
        ),
    ]
