# Generated by Django 4.2.4 on 2023-08-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0006_settings_exclusions_settings_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesajob',
            name='pid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
