# Generated by Django 4.2.4 on 2023-08-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0007_mesajob_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesajob',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
